### PR TITLE
Added caution for Android Appsflyer DI

### PR DESCRIPTION
**Pull request by ankit-saxena**
Caution to ensure that fingerprinting is enabled on the Appsflyer Android app for Branch to attribute installs properly.

### CODE REVIEW

**Comment by ankit-saxena** [comment]
@wlindemann

**Comment by ankit-saxena** [comment]
No. It's something that Appsflyer switches from their backend. It's not on
their dashboard.

**Comment by wlindemann** [comment]
That'll do. Added 👍

**Comment by Sarkar** [comment]
shipit 👍

**Pull request merged**
