### PR TITLE
custom domain updates and UL cleanup

### PR DESCRIPTION
**Pull request by wlindemann**
@aeromusek @lilabjorg @dmitrig01 @derrickstaten

Updates to custom domain instructions + UL

**Needs two more things:**

- [x] New screenshot with highlights to replace this (either I'm doing something wrong or preview doesn't like multiple highlights): https://dev.branch.io/img/pages/getting-started/dashboard-guide/custom_link_domain.png
- [ ] Needs redirect from https://dev.branch.io/getting-started/universal-app-links/advanced/ios/#using-a-custom-domain-or-subdomain to https://dev.branch.io/getting-started/dashboard-guide/guide/#setting-a-custom-link-domain

In this commit:

- Removed custom root + subdomain from UL set up (it's now one setup for everyone, hence request for redirect)
- Removed pro tip links that pointed to custom domain reference in UL Advanced 
- For dashboard domain set up: split custom domain set up into root + subdomain
- Added nameserver information for root domain + image
- Added SSL information tip
- Removed CloudFlare references (now unnecessary)
- Added UL validator to the custom domain error checker

### CODE REVIEW

**Comment by aeromusek** [comment]
Ohhh nice. I literally had just added this to my list to ask about tomorrow morning.

I'll take care of the new example screenshot.

**Comment by lilabjorg** [comment]
Redirect should be:

<RoutingRule>
  <Condition>
    <KeyPrefixEquals>universal-app-links/advanced/ios/#using-a-custom-domain-or-subdomain</KeyPrefixEquals>
  </Condition>
  <Redirect>
      <HostName>dev.branch.io</HostName>
    <ReplaceKeyPrefixWith>dashboard-guide/guide/#setting-a-custom-link-domain</ReplaceKeyPrefixWith>
  </Redirect>
</RoutingRule>

But I'm about to split dashboard-guide into several pages for custom events.

**Comment by aeromusek** [comment]
Can we even do redirects from anchor tags?

**Comment by lilabjorg** [comment]
I'm not sure - we haven't bothered in the past. I actually think it's somewhat of a waste given how often we're likely to change those titles.

**Comment by aeromusek** [comment]
I agree :+1:.

From what little I know, and assuming AWS is the same as regular redirects, the #anchor part of the URL doesn't even get sent to the server.

**Comment by lilabjorg** [comment]
Google search says that too.

**Comment by aeromusek** [comment]
Hey guys, status on this one? Since the redirect isn't possible, I'd vote to just merge this anway

**Comment by lilabjorg** [comment]
Yes, I say go ahead @aeromusek

**Pull request merged**
