### PR TITLE
max fixed youtube

### PR DESCRIPTION
**Pull request by derrickstaten**
@jakecadams I don't know about plugins, can you double-check this for prod?

### CODE REVIEW

**Comment by MaxwellLevenson** [comment]
Please look this over. It looks bad on the portal

**Comment by dmitrig01** [comment]
cna you take a screenshot? what does it need? better css or something else?

**Comment by MaxwellLevenson** [comment]
I meant that this fix makes it look better. The current embedding makes it so that you have to actually GO to Youtube to watch the video and on our site it looks like its just stopped at 40s. This fix makes it playable from our site.

**Comment by dmitrig01** [comment]
oh! nice!

**Comment by dmitrig01** [comment]
you wrote the ruby? that's awesome!

I didn't actually run it but code-wise it looks good :+1:. if derrick ran it and it looks good, let's do it!

**Comment by MaxwellLevenson** [comment]
I wish, I pulled it off a webpage...

**Comment by dmitrig01** [comment]
@derrickstaten you tested this?

**Comment by derrickstaten** [comment]
let me test

**Comment by derrickstaten** [comment]
It works. I tagged @jakecadams because I don't know how plugins work. I guess "magic" is the answer. :+1:

**Pull request merged**
