### PR TITLE
adding encouragement to stick with one subdomain

### PR DESCRIPTION
**Pull request by jeanmw**
@derrickstaten @aaustin let me know if this wording is good to go. Thanks!

### CODE REVIEW

**Comment by aeromusek** [comment]
Flag on the submodule reference for `branch-web-assets`...looks like it got pointed back at an old branch, which will cause some fireworks if deployed :smiling_imp:

**Comment by derrickstaten** [comment]
@jeanmw can you uncommit the change to branch-web-assets? then this looks fine. we had a bigger warning before but this will do for now.

**Comment by jeanmw** [comment]
hey, yeah I have no idea how that happened, but yes I will do that now @aeromusek @derrickstaten

**Comment by aeromusek** [comment]
@jeanmw we ran into some weirdness with local merges after the new portal went live...I think the changes were just so drastic that git couldn't figure out what to do. I'm guessing this is just a lingering effect of that

**Comment by jeanmw** [comment]
@aeromusek thanks for letting me know - would it be better just to get rid of this PR completely and make a new branch/PR? It would be easy, it's a one line change here

**Comment by aeromusek** [comment]
That would be one option! Otherwise it's a pretty easy fix:

1.  `cd` into the `_includes/branch-web-assets` directory
1. Check out the `new-design-lila` and make sure you have the latest pulled
1. `cd` back to the documentation repo root
1. Add change and then commit it

After that, it should be pointing to a53d47aa676f464c34586900a11fbeb7596f5b05

**Comment by jeanmw** [comment]
hm I have tried this but can't pull from the remote new-design-lila branch - going to try this again

**Pull request closed without merging**
