### PR TITLE
TUNE Final QA and some other JS additions for Dynamic Link Builder

### PR DESCRIPTION
**Pull request by AustinHay**
@Johnjoe220 @Sarkar  cc Scot dinn... not sure what your ghub handle is.

A

### CODE REVIEW

**Comment by Sarkar** [comment]
@AustinHay ack - identity will actually just be ` {{ identity.~id }}`. mind making that change, please?

**Comment by scott-branchio** [comment]
@Sarkar I tried updating an existing production BMF webhook with user_id={{identity.~id}} and when saving the webhook the backend returns server error 500...so I don't think we want to change the template to use that value.

**Comment by Sarkar** [comment]
apologies - it's actually `{{ identity.id }}`

**Comment by AustinHay** [comment]
Good to pull @Sarkar @aeromusek

**Pull request merged**
