### PR TITLE
Expand App Links troubleshooting steps

### PR DESCRIPTION
**Pull request by aeromusek**
@aaustin we had a Jekyll formatting issue. Fixed here, and added a few more details. Since you're the App Links expert, could you verify this?

### CODE REVIEW

**Comment by aaustin** [comment]
Looks good :+1:

**Comment by aaustin** [comment]
Looks like there are conflicts

**Comment by aeromusek** [comment]
@aaustin merge conflicts? I'm not seeing anything....

**Comment by aaustin** [comment]
interesting - it showed them from my phone : /

**Pull request merged**
