### PR TITLE
Docs for the new Yandex AppMetrica DI integration.

### PR DESCRIPTION
**Pull request by Zhukn1**
Waiting on this PR to merge: https://github.com/BranchMetrics/dashboard/pull/535

### CODE REVIEW

**Comment by Zhukn1** [comment]
@wlindemann I think the docs on AppMetrica are finished. Can you please take a look?

I already put the link on the sidebar. I can take it out until after we launch the PR piece. What do you think is best?

**Comment by wlindemann** [comment]
Looks great! Is this section correct for AppMetrica? Looks like a copy of Tune, so I'm just checking we didn't miss something:
http://localhost:4000/third-party-integrations/appmetrica/advanced/#what-branch-sends-to-appmetrica

Troubleshooting steps would be great too, but this should be fine for now.

**Comment by Zhukn1** [comment]
@wlindemann the parameters are exactly the same, that's why I copied them. 

I want to loop in the AppMetrica support team as much as I can for the after-launch stage. I'm very confident that questions will probably on that side. 
Will keep track of the incoming requests and I'll add the advanced section when we see some repeating ones coming in.

**Comment by wlindemann** [comment]
Overall 👍

**Comment by Sarkar** [comment]
👍

**Pull request merged**
