### PR TITLE
New troubleshooting steps

### PR DESCRIPTION
**Pull request by aeromusek**
@derrickstaten

### CODE REVIEW

**Comment by derrickstaten** [comment]
Can you add info about #4 from their email? Apparently there are two tools and one is completely broken

**Comment by aeromusek** [comment]
We already cover the tool that works and call out the tool that doesn't work elsewhere on the page (so that section is not showing up in the diff). Do you want them added a second time?

**Comment by derrickstaten** [comment]
oh weird, I wonder why these guys didn't see it. okay! :+1:

On Tue, Apr 19, 2016 at 4:33 PM, Alex Bauer <notifications@github.com>
wrote:

> We already cover the tool that works and call out the tool that doesn't
> work elsewhere on the page (so that section is not showing up in the diff).
> Do you want them added a second time?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/BranchMetrics/documentation/pull/246#issuecomment-212171101>
>



-- 
[image: Branch] <https://branch.io/?bmp=xink-sig>
Derrick Staten
Engineer
What is deep linking? <https://t.xink.io/Tracking/Index/Kg4AAGZBAABoTAYA0>
Check out our webinars <https://t.xink.io/Tracking/Index/Kw4AAGZBAABoTAYA0>

**Comment by aeromusek** [comment]
I was wondering the same thing! Oh well

**Pull request merged**
