### PR TITLE
Google Search Ads documentation update

### PR DESCRIPTION
**Pull request by amruta-d**
Updated the documentation to add details on how to get the Branch link id in case of Android only Search ads. It was mentioned on the Google UAC page but not on this page.

@ethanneff : Could you please review.

### CODE REVIEW

**Comment by aaustin** [comment]
Can you use an app.link example?

**Comment by amruta-d** [comment]
Sure Alex. I will update it with an app.link example.

**Comment by amruta-d** [comment]
@aaustin updated the example with app.link.

**Comment by ethanneff** [comment]
👍

**Pull request merged**
