### PR TITLE
Contact section added under side navigation bar

### PR DESCRIPTION
**Pull request by CodingAspect**
Merge of submodule to main repo.
@dmitrig01

### CODE REVIEW

**Comment by dmitrig01** [comment]
would love to see a screenshot :-)

**Comment by CodingAspect** [comment]
contact-widget

**Comment by dmitrig01** [comment]
@wlindemann ^

**Comment by derrickstaten** [comment]
:+1:

**Comment by derrickstaten** [comment]
@CodingAspect can you merge master locally into this branch then push it up? sorry for the slow response here

**Comment by CodingAspect** [comment]
@derrickstaten 
Pushed ^

**Comment by derrickstaten** [comment]
so excited to have this. thanks!

**Pull request merged**
