### PR TITLE
moar and better docs

### PR DESCRIPTION
**Pull request by wlindemann**
DO NOT MERGE 

@derrickstaten can you take a gander and edit the code snippet plz. I can then update Responsys docs too.

### CODE REVIEW

**Comment by derrickstaten** [comment]
modified. is this only for sailthru for now?

**Comment by wlindemann** [comment]
@aeromusek pretty meaty - I can review tomorrow when I'm a bit sharper, but thought you'd like to see since it's going in the sidebar.

**Comment by wlindemann** [comment]
CC @derrickstaten

**Comment by aeromusek** [comment]
@wlindemann nice!

I tweaked a few little formatting things, but it looks great to me. Thanks for not making me write all this 😀

**Pull request merged**
